=== dev-celo2/others/webapps/onbyte/WEB-INF/classes/conf/rolesMappings.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.0">
    <xs:element name="mappings" >
        <xs:complexType>
            <xs:sequence>               
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="profile"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="profile">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="1" minOccurs="0" ref="grouptype"/>                    
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="grouptype">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="group"/>                    
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>            
        </xs:complexType>
    </xs:element>
    
    <xs:element name="group">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="1" minOccurs="0" ref="role"/>                    
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>            
        </xs:complexType>
    </xs:element>
    
    <xs:element name="role" >
        <xs:complexType>           
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>   
</xs:schema>

=== dev-celo2/others/webapps/onbyte/WEB-INF/classes/conf/rolesMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="rolesMappings.xsd">
	<profile name="admin">
		<grouptype name="SYSMGMT">
			<group name="USER">
				<role name="manager"/>
			</group>
			<group name="CUSTOMER">
				<role name="manager"/>
			</group>
		</grouptype>
	</profile>

	<profile name="operator">
		<grouptype name="SYSMGMT">
			<group name="USER"/>
			<group name="CUSTOMER"/>
		</grouptype>
	</profile>

</mappings>
